default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV['RAILS_MAX_THREADS'] || 30 %>

development:
  <<: *default
  database: grudges_development
  pool: 30
  timeout: 5000

production:
  <<: *default
  database: grudge_production
  username: grudges
  password: <%= ENV['GRUDGE_BASE_PASSWORD'] %>
  pool: 30
